name: CommonLib
on:
  push:
    branches: [ main ]
jobs:
  build:
    name: "${{matrix.system}}-${{matrix.architecture}}-${{matrix.configuration}}"
    runs-on: ${{matrix.image}}
    strategy:
      matrix:
        system: [ Windows ]
        architecture: [ x86, x64 ]
        configuration: [ Debug, Release ]
        image: [ windows-2025-vs2026 ]
    steps:
    - name: Clone
      uses: actions/checkout@v7
      with:
        submodules: true
    - name: Install Python
      uses: actions/setup-python@v7
      with:
        python-version: "3.13"
    - name: Install Python packages
      working-directory: ${{github.workspace}}
      run: pip install -r Requirements.txt
    - name: Build
      working-directory: ${{github.workspace}}
      run: ./CommonLib.bat build --target_os ${{matrix.system}} --target_arch ${{matrix.architecture}} --target_config ${{matrix.configuration}}
    - name: Upload artifacts
      uses: actions/upload-artifact@v7
      with:
        name: "CommonLib-${{matrix.system}}-${{matrix.architecture}}-${{matrix.configuration}}.zip"
        retention-days: 90
        path: |
          include/
          lib/
          thirdparty/**/include/**
          LICENSE
          !**/.*
          !**/CMake*
