name: Validate

on:
  push:
    branches: [ main ]

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    
    steps:
    - name: Clone
      uses: actions/checkout@v7
      with:
        submodules: true
    
    - name: Install Cppcheck
      run: |
        sudo apt-get update
        sudo apt-get install -y cppcheck
    
    - name: Install Python
      uses: actions/setup-python@v7
      with:
        python-version: "3.14"
    
    - name: Install Python packages
      working-directory: ${{github.workspace}}
      run: pip install -r Requirements.txt

    - name: Validate
      working-directory: ${{github.workspace}}/tools/scripts/cli
      run: py ./main.py validate --skip_submodules
